---
roles:
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0

collections:
  - name: community.general
    version: 9.0.0
  - name: community.crypto
    version: 2.20.0
  - name: geerlingguy.mac
    version: 1.4.0
